### ISSUE TITLE
File downloading failed: bind address already in use

### ISSUE THREAD

**Issue by declmal** [CortexFoundation/torrentfs#61]
I managed to seed the file to dht,  but it seems that the file still cannot be downloaded while I'm testing `dolores`.

So , I followed the README.md on branch `master`:

It seems seeding is successful:
```
^C(py37) ryt@dev-server:~/ryt/torrentfs/build/bin$ ./seeding -dataDir=store
2020/07/06 10:25:27 main.go:290: 0803be8fc7309d155dfcee65a92a6254bd55a3d2 is seeding
```

But error occurs when downloading, it reports as follows:
```
(py37) ryt@dev-server:~/ryt/torrentfs/build/bin$ ./torrent download 'infohash:0803be8fc7309d155dfcee65a92a6254bd55a3d2'
2020-07-06T10:25:53+0800 NONE  main.go:210: error in main: creating client: first listen: listen tcp4 :42069: bind: address already in use
```

**Comment by ucwong** [comment]
Check the port 42069

**Comment by ucwong** [comment]
```0803be8fc7309d155dfcee65a92a6254bd55a3d2 ``` is only example file hash, you should use the file's info hash you want to seed

**Comment by declmal** [comment]
Yes, I have done it exactly.

**Comment by declmal** [comment]
> Check the port 42069, it seems already being used by others

<img width="1422" alt="屏幕快照 2020-07-06 上午11 17 13" src="https://user-images.githubusercontent.com/34788594/86552363-5e771800-bf7a-11ea-9590-57c77678055c.png">

**Comment by declmal** [comment]
> > Check the port 42069, it seems already being used by others
> 
> <img alt="屏幕快照 2020-07-06 上午11 17 13" width="1422" src="https://user-images.githubusercontent.com/34788594/86552363-5e771800-bf7a-11ea-9590-57c77678055c.png">

It's
```
udp        0      0 0.0.0.0:42069           0.0.0.0:*                           88301/./torrentfs/b
```

**Comment by ucwong** [comment]
Try to restart seeding and downloading

**Comment by declmal** [comment]
Ok

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/86552802-992d8000-bf7b-11ea-9cfc-135ee78446ff.png)
I have done it right

**Comment by declmal** [comment]
> ![image](https://user-images.githubusercontent.com/22344498/86552842-bb270280-bf7b-11ea-998a-7cf42c0a068e.png)
> 
> ![image](https://user-images.githubusercontent.com/22344498/86552802-992d8000-bf7b-11ea-9cfc-135ee78446ff.png)
> I have done it right

May I see your complete command for `./torrent download` ?

**Comment by ucwong** [comment]
![image](https://user-images.githubusercontent.com/22344498/86553107-5a4bfa00-bf7c-11ea-84d1-4967c09a4c3e.png)

**Comment by ucwong** [comment]
You can pull the new code to try again, if you still can't download it

**Comment by declmal** [comment]
Finally, successfully downloaded, thx!
