### ISSUE TITLE
can't run sucessfully

### ISSUE THREAD

**Issue by ShadowErii** [CortexFoundation/torrentfs#64]
i did as the readme file,and after i seeding file to dht,i try to download,it can bootstrap successfully but discovered 0 upnp devices(portfwd.go)

**Comment by ShadowErii** [comment]
<img width="987" alt="截屏2020-07-17 下午3 38 47" src="https://user-images.githubusercontent.com/21995734/87761618-59e91400-c844-11ea-8433-4fb8b55e67d2.png">

<img width="825" alt="截屏2020-07-17 下午3 43 05" src="https://user-images.githubusercontent.com/21995734/87761687-7b4a0000-c844-11ea-8ee1-f60b4ba5ceaa.png">

**Comment by ucwong** [comment]
https://github.com/CortexFoundation/torrentfs/issues/61

**Comment by ucwong** [comment]
Just wait for a moment

**Comment by ShadowErii** [comment]
<img width="991" alt="截屏2020-07-18 上午11 02 43" src="https://user-images.githubusercontent.com/21995734/87843604-83f41200-c8e8-11ea-8dbf-65aba7470857.png">
it takes too long...

**Comment by ucwong** [comment]
> <img alt="截屏2020-07-18 上午11 02 43" width="991" src="https://user-images.githubusercontent.com/21995734/87843604-83f41200-c8e8-11ea-8dbf-65aba7470857.png">
> 
> it takes too long...

For the number of seeding resources or poor network of seeding
